---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
    driver:
      network:
        - ["private_network", {ip: "192.168.103.95"}]

suites:
  - name: default
    run_list:
      - recipe[wordpress-simple::default]
    attributes:
