name             'wordpress-simple'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures wordpress-simple'
long_description 'Installs/Configures wordpress-simple'
version          '0.1.0'

depends 'mysql2_chef_gem'
depends 'mysql'
depends 'database'
depends 'tar'